
<!-- FUNCTION #1: -->
```{r}
get_playlist <- function(playlist_id,
                         fields = NULL,
                         market = NULL,
                         authorization = get_spotify_access_token()
                         ) {
    base_url <- 'https://api.spotify.com/v1/playlists'
    url <- str_glue('{base_url}/{playlist_id}')

    params <- list(
        fields = paste(fields, collapse = ','),
        market = market,
        access_token = authorization
    )

    # stopping is built into query_playlist()
    init_query <- query_playlist(url, params = params)
    # identify how many pages there are
    total_tracks <- pluck(init_query, "tracks", "total")
    if (total_tracks > 100) {
        n_pages <- total_tracks %/% 100
        # identify pagination offsets
        offsets <- seq(from = 1, to = n_pages) * 100
        # create page urls
        page_urls <- str_glue("{url}/tracks?offset={offsets}&limit=100")
        # query api
        other_pages <- map(page_urls, query_playlist, params)
        # merge the song track results
        all_items <- bind_rows(
            pluck(init_query, "tracks", "items"),
            map_dfr(other_pages, pluck, "items")
        )

        # overwrite init_query item results
        init_query[["tracks"]][["items"]] <- all_items
    }
    #return init_query object
    structure(init_query, class = c("playlist", "list"))
}
```


<!-- Function #2: COMPLETED -->
1. Input 
- playlist_id = playlist id
- fields = 
- limit = max number of tracks shown
- offset = first index of tracks
- market = country abbreviation
- authorization = spotify access token
- include_meta_info = 

2. f
3. f
4. f
5. f
6. f
7. f
```{r}
get_playlist_tracks <- function(playlist_id,
                                fields = NULL,
                                limit = 100,
                                offset = 0,
                                market = NULL,
                                authorization = get_spotify_access_token(),
                                include_meta_info = FALSE) {
    # store link in a string variable called base_url;
    base_url <- 'https://api.spotify.com/v1/playlists'
    # combine string of base_url, playlist_id into one link in a string;
    url <- str_glue('{base_url}/{playlist_id}/tracks')
    # create a list called params to store variables: fields, limit, offset, market, access_token;
    params <- list(
        # if fields is NOT null, paste each element together with a comma between them,
        # and put the string 'items(' in the front and ')' at the end;
        # else make fields an empty string of '';
        # (paste0() function concatenates strings using no space as the default separator.)
        fields = ifelse(!is.null(fields), paste0('items(', paste0(fields, collapse = ','), ')'), ''),
        # set limit variable to what user sets or default of 100;
        limit = limit,
        # set limit variable to what user sets or default of 0;
        offset = offset,
        # set limit variable to what user sets or default of NULL;
        market = market,
        # set access_token to what user sets for authorization;
        access_token = authorization
    )

    # Reads/Gets URL with given query information and stores in res variable in json format;
    res <- RETRY('GET', url, query = params, encode = 'json')
    # Converts http errors to R errors or warnings - 
    # these should always be used whenever you're creating requests inside a function, 
    # so that the user knows why a request has failed.
    stop_for_status(res)
    # !
    res <- fromJSON(content(res, as = 'text', encoding = 'UTF-8'), flatten = TRUE)

    # if include_meta_info is FALSE, store items of json into res udpated var;
    if (!include_meta_info) {
        res <- res$items
    }
    # return the items in the json;
    return(res)
}
```


<!-- FUNCTION #3: -->
```{r}
get_my_playlists <- function(limit = 20,
                             offset = 0,
                             authorization = get_spotify_authorization_code(),
                             include_meta_info = FALSE) {

    base_url <- 'https://api.spotify.com/v1/me/playlists'
    params <- list(
        limit = limit,
        offset = offset
    )
    res <- RETRY('GET', base_url, query = params, config(token = authorization), encode = 'json')
    stop_for_status(res)
    res <- fromJSON(content(res, as = 'text', encoding = 'UTF-8'), flatten = TRUE)

    if (!include_meta_info) {
        res <- res$items
    }

    res
}
```