
Inputs:
- Vector of genre(s) in string/character format (See possibilities from get_possible_genres() but not all genres works)
- Limit of top tracks in that genre; Up to 50 and minimum 1; Default 20 of top tracks;
- Spotify Access Token

Return:
- Violin Plot(s) of Inputted Genres with Genres on X-Axis and Danceability Number on Y-Axis with Legend;
```{r}
create_violin_plot_genre_danceability <- function(genres, limit=20, authorization = get_spotify_access_token()) {
    list_df_genres <- genres %>% 
                        purrr::map(~ get_genre_track_features(.x, limit=limit, authorization=authorization) %>% mutate(genre = .x))
    
    df_genres <- bind_rows(list_df_genres)

    if (length(genres) <= 5) {
        gg <- ggplot2::ggplot(df_genres, aes(x=genre, y=danceability))  + 
                ggplot2::geom_violin(aes(fill = genre)) + 
                labs(title = "Danceability of Genre Top Tracks", x = "Genre", y = "Danceability", fill = "Genre") + 
                theme(plot.title = element_text(hjust = 0.5)) + 
                stat_summary(fun.data = "mean_cl_normal", geom = "point", shape = 20, size = 4, color = "red")
    } 
    else {
        gg <- ggplot2::ggplot(df_genres, aes(x=genre, y=danceability))  + 
                ggplot2::geom_violin(aes(fill = genre)) + 
                labs(title = "Danceability of Genre Top Tracks", x = "") + 
                theme(plot.title = element_text(hjust = 0.5), 
                        axis.text.x=element_blank(), 
                        axis.ticks.x=element_blank()
                        ) + 
                stat_summary(fun.data = "mean_cl_normal", geom = "point", shape = 20, size = 4, color = "red")
    }
    plotly::ggplotly(gg)
}
```

```{r}
create_violin_plot_genre_danceability(c("hip-hop","pop","rock"), limit=50)
```


All Code Required Beforehand:
```{r}
library(spotifyr)
library(tidyverse)

Sys.setenv(SPOTIFY_CLIENT_ID = 'f995a310ad724cd49e6eb7a8736e7b19')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '9e60ab8050b945558219098bc9470925')

access_token <- get_spotify_access_token()

get_possible_genres <- function(authorization = get_spotify_access_token()){
    url <- "https://api.spotify.com/v1/recommendations/available-genre-seeds"
    parameters <- list(
        access_token = authorization
    )
    result = httr::RETRY(verb = "GET", url, query = parameters, encode = "json", terminate_on = c(401, 403, 404))
    httr::stop_for_status(result)
    result <- jsonlite::fromJSON(httr::content(result, as = "text", encoding = "UTF-8"), flatten = TRUE)
    result <- as.data.frame(result)
    result
}

get_genre_tracks <- function(genre, limit = 20, offset = 0, authorization = get_spotify_access_token()){
    url <- "https://api.spotify.com/v1/search"
    parameters <- list(
        q = stringr::str_glue('genre:"{genre}"'),
        type = "track",
        market = "US",
        limit = limit,
        offset = offset,
        access_token = authorization
    )

    result <- httr::RETRY("GET", url, query = parameters, encode = "json", terminate_on = c(401, 403, 404))

    httr::stop_for_status(result)

    result <- jsonlite::fromJSON(httr::content(result, as = 'text', encoding = 'UTF-8'),
                    flatten = TRUE)$tracks$items

    result$artists <- purrr::map(result$artists, ~ list(id = .x$id, name = .x$name))
    result <- result %>% 
            dplyr::mutate(
                artist_id = purrr::map_chr(artists, ~ toString(.x$id)),
                artist_name = purrr::map_chr(artists, ~ toString(.x$name))
                ) %>%
            dplyr::select(
                -artists,
                -href,
                -is_local,
                -is_playable,
                -preview_url,
                -disc_number,
                -uri,
                -album.artists,
                -album.href,
                -album.id,
                -album.images,
                -album.is_playable,
                -album.name,
                -album.release_date,
                -album.release_date_precision,
                -album.total_tracks,
                -album.type,
                -album.uri,
                -album.external_urls.spotify,
                -external_ids.isrc,
                -external_urls.spotify
            ) %>%
            dplyr::rename(
                track_id = id,
                track_name = name,
                album_type = album.album_type
            )
    result
}

get_track_audio_features <- function(ids, authorization = get_spotify_access_token()){
    assertthat::assert_that(
        length(ids) <= 100,
        msg = "The maximum length of the length of the ids vector is 100.  Please shorten the length of the inputed vector."
    )
    url <- 'https://api.spotify.com/v1/audio-features'
    parameters <- list(
        ids = paste0(ids, collapse = ','),
        access_token = authorization
    )
    result <- httr::RETRY('GET', url, query = parameters, encode = 'json')
    httr::stop_for_status(result)

    result <- jsonlite::fromJSON(httr::content(result, as = 'text', encoding = 'UTF-8'), flatten = TRUE)
    result <- result$audio_features %>% 
    dplyr::select(
        -type,
        -uri,
        -track_href,
        -analysis_url
    ) %>%
    dplyr::rename(
        track_id = id
    )

    result
}

get_genre_track_features <- function(genre, limit=20, authorization = get_spotify_access_token()){
    tracks <- get_genre_tracks(genre, limit=limit, authorization = authorization)
    features <- get_track_audio_features(tracks$track_id, authorization = authorization)

    result <- dplyr::left_join(tracks, features, by = "track_id") %>%
              dplyr::select(
                -duration_ms.x
              ) %>%
              dplyr::rename(
                duration_ms = duration_ms.y
                )

    result
}
```
