```{r}
create_artist_songs_radar_chart <- function(songs, vars = c(), colors = c(), authorization = get_spotify_access_token()){
  if (length(songs) > 5){
    stop("Please input only 5 or less tracks!")
  }
  create_beautiful_radarchart <- function(data, color = "#00AFBB", 
                                        vlabels = colnames(data), vlcex = 0.7,
                                        caxislabels = NULL, title = NULL, ...){
    fmsb::radarchart(
      data, axistype = 1,
      # Customize the polygon
      pcol = color, pfcol = scales::alpha(color, 0.5), plwd = 2, plty = 1,
      # Customize the grid
      cglcol = "grey", cglty = 1, cglwd = 0.8,
      # Customize the axis
      axislabcol = "grey", 
      # Variable labels
      vlcex = vlcex, vlabels = vlabels,
      caxislabels = caxislabels, title = title, ...
    )
  }

  min_max <- data.frame(
    row.names = c("min", "max"),
    valence = c(0, 1),
    energy = c(0, 1),
    speechiness = c(0, 1)
  )

  if (length(vars) > 0){
    create_data_frame <- function(var) {
      data.frame(
        var = c(0, 1)  
      )
    }

    combinations <- purrr::map_dfc(vars, create_data_frame) %>% 
                    dplyr::rename_with(~ vars, dplyr::everything())

    min_max <- cbind(min_max, combinations)
  }

  genre_summaries <- purrr::map(songs, ~ get_track_audio_features(.x, authorization = authorization))

  final_summary_df <- dplyr::bind_rows(genre_summaries)

  rownames(final_summary_df) <- songs

  final_summary_df <- final_summary_df %>%
                      dplyr::select(
                        valence,
                        energy,
                        speechiness,
                        vars
                      )
                      
  final_summary_df <- rbind(min_max, final_summary_df)  
  
  op <- par(mar = c(0, 0, 0, 0))
  
  create_beautiful_radarchart(
    data = final_summary_df, caxislabels = c(0, 0.25, 0.50, 0.75, 1),
    color = colors,
    vlcex = 1.5
  )
  
  tracks <- purrr::map(songs, get_tracks) %>% 
    as.data.frame() %>% 
    dplyr::select(
        track_name,
        track_name.1,
        track_name.2,
        track_name.3,
        track_name.4
    )
  tracks <- tidyr::pivot_longer(tracks, cols = starts_with("track_name"), 
                          names_to = "track_names", values_to = "names")
  legend(
    x = "bottom", legend = tracks$names, horiz = TRUE,
    bty = "n", pch = 20 , col = colors,
    text.col = "black", cex = 0.5
    )

  par(op)
}
```

```{r}
View(create_artist_songs_radar_chart(songs = c("6YbhspuOar1D9WSSnfe7ds", "5Tbpp3OLLClPJF8t1DmrFD", "2NBQmPrOEEjA8VbeWOQGxO", "39QBkWKnap8wRSW4WB9OK0", "0xzI1KAr0Yd9tv8jlIk3sn"), vars = "liveness", colors = c("#2596BE", "#BC22BF", "#eb4034", "#31cc46", "#8c880f")))
```