
Shorter:

#' Creates Violin Plot for an Artist's Album for the variable Danceability.

#' UNIFNISHED FUNCTION: create limit parameter;

Inputs:
- artist id
- spotify access token (client id + client secret)

Returns:
- A violin plot of the albums of an artist based on Danceability from the Spotify API.

```{r}
create_violin_plot_album_danceability <- function(artist_id, authorization = get_spotify_access_token()){
    df_artist <- get_artist_audio_features(artist_id, authorization = authorization)
    
    # not based on size of input, but rather number of rows of df;
    # if (nrow(df_artist) <= 5)
    if(length(unique(df_artist$album_name)) <= 3) {
      ggplot2::ggplot(df_artist, aes(x=album_name, y=danceability))  + 
        ggplot2::geom_violin(aes(fill = album_name)) + 
        # can use springf or paste; equivalent of {} for var in string;
        labs(title = sprintf("Danceability of %s's Albums", df_artist$artist_name), x = "Album", y = "Danceability", fill = "Album") + 
        theme(plot.title = element_text(hjust = 0.5))
    } else {
      ggplot2::ggplot(df_artist, aes(x=album_name, y=danceability))  + 
        ggplot2::geom_violin(aes(fill = album_name)) + 
        labs(title = sprintf("Danceability of %s's Albums", df_artist$artist_name), x = "", y = "Danceability", fill = "Album") + 
        theme(plot.title = element_text(hjust = 0.5), 
              axis.text.x=element_blank(),
              axis.ticks.x=element_blank() 
        )
    }
}
```

```{r}
# library(devtools)
# install_github("AdamDelRio/SpotifyProject")
```

```{r}
# get_album()
```

TRY RUNNING IN WEEK 4 use function LIMIT test;

All Required Code to Run Beforehand:
```{r | new get_artist_audio_features function}
get_artist_audio_features <- function(id, authorization = get_spotify_access_token()){
    info <- get_artists(id, authorization = authorization)
    artist_id <- info$artist_id
    artist_name <- info$name
    if(is.null(artist_id)){
        stop("No artist found with inputed ID.  Please try again with a different ID.")
    }
    albums <- get_artist_projects(artist_id, authorization = authorization)
    if (is.null(albums) | length(albums)==0) {
        stop("No albums found with inputed ID.  Please try again with a different ID.")
    }
    num_loops <- ceiling(nrow(albums) / 50)
    if (num_loops > 1) {
        albums <- purrr::map_df(1:num_loops, function(this_loop) {
            get_artist_projects(artist_id,
                              offset = (this_loop - 1) * 50,
                              authorization = authorization)
        })
    }
    albums <- albums %>%
        dplyr::mutate(
          album_release_year = dplyr::case_when(
              release_date_precision == 'year' ~ suppressWarnings(as.numeric(release_date)),
              release_date_precision == 'day' ~ lubridate::year(
                            as.Date(release_date, '%Y-%m-%d',
                                    origin = '1970-01-01')),
              TRUE ~ as.numeric(NA))
        )
        suppressWarnings({
        tracks <- purrr::map_df(albums$album_id, function(album_id) {
            tracks <- get_albums_tracks(album_id,
                                            authorization = authorization)
            num_loops <- ceiling(nrow(tracks) / 20)
                if (num_loops > 1) {
                    tracks <- purrr::map_df(1:num_loops, function(this_loop) {
                        get_albums_tracks(album_id,
                                        offset = (this_loop - 1) * 20,
                                        authorization = authorization)
        })} 
        tracks <- tracks %>%
                dplyr::mutate(
                album_id = album_id,
                album_name = paste(albums$album_name[albums$album_id == album_id], collapse = ", ")
                ) %>%
                dplyr::distinct(track_name, .keep_all = TRUE)
        })
    })
    num_loops_tracks <- ceiling(nrow(tracks) / 100)

    track_audio_features <- purrr::map_df(1:num_loops_tracks, function(this_loop) {
        track_ids <- tracks %>%
            dplyr::slice(((this_loop * 100) - 99):(this_loop * 100)) %>%
            dplyr::pull(track_id)
        get_track_audio_features(track_ids, authorization = authorization)
    }) %>%
        dplyr::left_join(tracks, by = 'track_id') %>%
        dplyr::select(-album_name)

    albums %>%
        dplyr::mutate(
            artist_name = artist_name,
            artist_id = artist_id
    ) %>%
        dplyr::select(
            artist_name,
            artist_id,
            album_id,
            album_release_date = release_date,
            album_release_year,
            album_release_date_precision = release_date_precision,
            album_name
    ) %>%
        dplyr::left_join(track_audio_features, by = 'album_id') %>%
        dplyr::mutate(key_name = pitch_class_lookup[key + 1],
            mode_name = dplyr::case_when(mode == 1 ~ 'major',
                                    mode == 0 ~ 'minor',
                                    TRUE ~ as.character(NA)),
            key_mode = paste(key_name, mode_name)) %>%
        dplyr::select(-artist_name.y,
                      -artist_id.y,
                      -duration_ms.y,
                      -is_playable) %>%
        dplyr::rename(artist_name = artist_name.x,
                      artist_id = artist_id.x,
                      duration_ms = duration_ms.x)
}
```

```{r charlie}
# family musicology functions
# importFrom rlang .data
# export
get_artist_audio_features <- function(artist = NULL,
                                      include_groups = 'album',
                                      return_closest_artist = TRUE,
                                      dedupe_albums = TRUE,
                                      market = NULL,
                                      authorization = get_spotify_access_token()
                                      ) {

    artist_id <- NULL

    if (is_uri(artist)) {
        artist_info <- get_artist(artist, authorization = authorization)
        artist_id <- artist_info$id
        artist_name <- artist_info$name
    } else {
        # Try to find an artist  with this ID
        artist_ids <- search_spotify(
            artist, 'artist',
            authorization = authorization)

        if (return_closest_artist) {
            artist_id <- artist_ids$id[1]
            artist_name <- artist_ids$name[1]
        } else {
            choices <- map_chr(1:length(artist_ids$name), function(x) {
                str_glue('[{x}] {artist_ids$name[x]}')
            }) %>% paste0(collapse = '\n\t')
            cat(str_glue('We found the following artists on Spotify matching "{artist}":\n\n\t{choices}\n\nPlease type the number corresponding to the artist you\'re interested in.'), sep  = '')
            selection <- as.numeric(readline())
            artist_id <- artist_ids$id[selection]
            artist_name <- artist_ids$name[selection]
        }
    }


    if (is.null(artist_id)) {
        stop("No artist found with artist_id='", artist_id, "'.")
    }

    artist_albums <- get_artist_albums(id = artist_id,
                                       include_groups = include_groups,
                                       include_meta_info = TRUE,
                                       market = market,
                                       authorization = authorization)


    if (is.null(artist_albums$items) | length(artist_albums$items)==0) {
        stop("No albums found with with artist_id='", artist_id, "'.")
    }


    num_loops_artist_albums <- ceiling(artist_albums$total / 20)

    if (num_loops_artist_albums > 1) {
        artist_albums <- map_df(1:num_loops_artist_albums, function(this_loop) {
            get_artist_albums(artist_id,
                              include_groups = include_groups,
                              offset = (this_loop - 1) * 20,
                              authorization = authorization)
        })
    } else {
        artist_albums <- artist_albums$items
    }

    artist_albums <- artist_albums %>%
        dplyr::rename(
          album_id = .data$id,
          album_name = .data$name
        ) %>%
        dplyr::mutate(
          album_release_year = case_when(
              release_date_precision == 'year' ~ suppressWarnings(as.numeric(.data$release_date)),
              release_date_precision == 'day' ~ lubridate::year(
                            as.Date(.data$release_date, '%Y-%m-%d',
                                    origin = '1970-01-01')),
              TRUE ~ as.numeric(NA))
        )

    if (dedupe_albums) {
        artist_albums <- dedupe_album_names(df = artist_albums)
    }

    album_tracks <- purrr::map_df(artist_albums$album_id, function(this_album_id) {
        album_tracks <- get_album_tracks(this_album_id,
                                         include_meta_info = TRUE,
                                         authorization = authorization)

        num_loops_album_tracks <- ceiling(album_tracks$total / 20)
        if (num_loops_album_tracks > 1) {
            album_tracks <- purrr::map_df(1:num_loops_album_tracks, function(this_loop) {
                get_album_tracks(this_album_id,
                                 offset = (this_loop - 1) * 20,
                                 authorization = authorization)
            })
        } else {
            album_tracks <- album_tracks$items
        }

        album_tracks <- album_tracks %>%
            dplyr::mutate(
              album_id = this_album_id,
              album_name = artist_albums$album_name[artist_albums$album_id == this_album_id]
            ) %>%
            dplyr::rename(
              track_name = name,
              track_uri = uri,
              track_preview_url = preview_url,
              track_href = href,
              track_id = id
            )
    })

    dupe_columns <- c('duration_ms', 'type', 'uri', 'track_href')

    num_loops_tracks <- ceiling(nrow(album_tracks) / 100)

    track_audio_features <- map_df(1:num_loops_tracks, function(this_loop) {
        track_ids <- album_tracks %>%
            dplyr::slice(((this_loop * 100) - 99):(this_loop * 100)) %>%
            dplyr::pull(.data$track_id)
        get_track_audio_features(track_ids, authorization = authorization)
    }) %>%
        dplyr::select(-dplyr::all_of( dupe_columns )) %>%
        dplyr::rename(track_id = .data$id) %>%
        dplyr::left_join(album_tracks, by = 'track_id')

    artist_albums %>%
        dplyr::mutate(
          artist_name = artist_name,
          artist_id = artist_id
        ) %>%
        dplyr::select(
          .data$artist_name,
          .data$artist_id,
          .data$album_id,
          .data$album_type,
          album_images = .data$images,
          album_release_date = .data$release_date,
          .data$album_release_year,
          album_release_date_precision = .data$release_date_precision
        ) %>%
        dplyr::left_join(track_audio_features, by = 'album_id') %>%
        dplyr::mutate(key_name = pitch_class_lookup[key + 1],
               mode_name = case_when(mode == 1 ~ 'major',
                                     mode == 0 ~ 'minor',
                                     TRUE ~ as.character(NA)),
               key_mode = paste(key_name, mode_name))
}
```

```{r}
get_artist_audio_features <- function(artist = NULL, 
                                      limit = 20,
                                      include_groups = 'album',
                                      return_closest_artist = TRUE,
                                      dedupe_albums = TRUE,
                                      market = NULL,
                                      authorization = get_spotify_access_token()
                                      ) {

    artist_id <- NULL

    if (is_uri(artist)) {
        artist_info <- get_artist(artist, authorization = authorization)
        artist_id <- artist_info$id
        artist_name <- artist_info$name
    } else {
        # Try to find an artist  with this ID
        artist_ids <- search_spotify(
            artist, 'artist',
            authorization = authorization)

        if (return_closest_artist) {
            artist_id <- artist_ids$id[1]
            artist_name <- artist_ids$name[1]
        } else {
            choices <- map_chr(1:length(artist_ids$name), function(x) {
                str_glue('[{x}] {artist_ids$name[x]}')
            }) %>% paste0(collapse = '\n\t')
            cat(str_glue('We found the following artists on Spotify matching "{artist}":\n\n\t{choices}\n\nPlease type the number corresponding to the artist you\'re interested in.'), sep  = '')
            selection <- as.numeric(readline())
            artist_id <- artist_ids$id[selection]
            artist_name <- artist_ids$name[selection]
        }
    }


    if (is.null(artist_id)) {
        stop("No artist found with artist_id='", artist_id, "'.")
    }

    artist_albums <- get_artist_albums(id = artist_id,
                                       include_groups = include_groups,
                                       include_meta_info = TRUE,
                                       market = market,
                                       limit = limit, # added this line;
                                       authorization = authorization)


    if (is.null(artist_albums$items) | length(artist_albums$items)==0) {
        stop("No albums found with with artist_id='", artist_id, "'.")
    }


    num_loops_artist_albums <- ceiling(artist_albums$total / 20)

    if (num_loops_artist_albums > 1) {
        artist_albums <- map_df(1:num_loops_artist_albums, function(this_loop) {
            get_artist_albums(artist_id,
                              include_groups = include_groups,
                              offset = (this_loop - 1) * 20,
                              authorization = authorization)
        })
    } else {
        artist_albums <- artist_albums$items
    }

    artist_albums <- artist_albums %>%
        dplyr::rename(
          album_id = .data$id,
          album_name = .data$name
        ) %>%
        dplyr::mutate(
          album_release_year = case_when(
              release_date_precision == 'year' ~ suppressWarnings(as.numeric(.data$release_date)),
              release_date_precision == 'day' ~ lubridate::year(
                            as.Date(.data$release_date, '%Y-%m-%d',
                                    origin = '1970-01-01')),
              TRUE ~ as.numeric(NA))
        )

    if (dedupe_albums) {
        artist_albums <- dedupe_album_names(df = artist_albums)
    }

    album_tracks <- purrr::map_df(artist_albums$album_id, function(this_album_id) {
        album_tracks <- get_album_tracks(this_album_id,
                                         include_meta_info = TRUE,
                                         authorization = authorization)

        num_loops_album_tracks <- ceiling(album_tracks$total / 20)
        if (num_loops_album_tracks > 1) {
            album_tracks <- purrr::map_df(1:num_loops_album_tracks, function(this_loop) {
                get_album_tracks(this_album_id,
                                 offset = (this_loop - 1) * 20,
                                 authorization = authorization)
            })
        } else {
            album_tracks <- album_tracks$items
        }

        album_tracks <- album_tracks %>%
            dplyr::mutate(
              album_id = this_album_id,
              album_name = artist_albums$album_name[artist_albums$album_id == this_album_id]
            ) %>%
            dplyr::rename(
              track_name = name,
              track_uri = uri,
              track_preview_url = preview_url,
              track_href = href,
              track_id = id
            )
    })

    dupe_columns <- c('duration_ms', 'type', 'uri', 'track_href')

    num_loops_tracks <- ceiling(nrow(album_tracks) / 100)

    track_audio_features <- map_df(1:num_loops_tracks, function(this_loop) {
        track_ids <- album_tracks %>%
            dplyr::slice(((this_loop * 100) - 99):(this_loop * 100)) %>%
            dplyr::pull(.data$track_id)
        get_track_audio_features(track_ids, authorization = authorization)
    }) %>%
        dplyr::select(-dplyr::all_of( dupe_columns )) %>%
        dplyr::rename(track_id = .data$id) %>%
        dplyr::left_join(album_tracks, by = 'track_id')

    artist_albums %>%
        dplyr::mutate(
          artist_name = artist_name,
          artist_id = artist_id
        ) %>%
        dplyr::select(
          .data$artist_name,
          .data$artist_id,
          .data$album_id,
          .data$album_type,
          album_images = .data$images,
          album_release_date = .data$release_date,
          .data$album_release_year,
          album_release_date_precision = .data$release_date_precision
        ) %>%
        dplyr::left_join(track_audio_features, by = 'album_id') %>%
        dplyr::mutate(key_name = pitch_class_lookup[key + 1],
               mode_name = case_when(mode == 1 ~ 'major',
                                     mode == 0 ~ 'minor',
                                     TRUE ~ as.character(NA)),
               key_mode = paste(key_name, mode_name))
}
```
