```{r | new get_possible_genres}
get_possible_genres <- function(authorization = get_spotify_access_token()){
    url <- "https://api.spotify.com/v1/recommendations/available-genre-seeds"
    parameters <- list(
        access_token = authorization
    )
    result = httr::RETRY(verb = "GET", url, query = parameters, encode = "json", terminate_on = c(401, 403, 404))
    httr::stop_for_status(result)
    result <- jsonlite::fromJSON(httr::content(result, as = "text", encoding = "UTF-8"), flatten = TRUE)
    result <- as.data.frame(result)
    result
}
```

```{r | new get_genre_tracks}
get_genre_tracks <- function(genre, limit = 20, offset = 0, authorization = get_spotify_access_token()){
    url <- "https://api.spotify.com/v1/search"
    parameters <- list(
        q = stringr::str_glue('genre:"{genre}"'),
        type = "track",
        market = "US",
        limit = limit,
        offset = offset,
        access_token = authorization
    )

    result <- httr::RETRY("GET", url, query = parameters, encode = "json", terminate_on = c(401, 403, 404))

    httr::stop_for_status(result)

    result <- jsonlite::fromJSON(httr::content(result, as = 'text', encoding = 'UTF-8'),
                    flatten = TRUE)$tracks$items

    result$artists <- purrr::map(result$artists, ~ list(id = .x$id, name = .x$name))
    result <- result %>% 
            dplyr::mutate(
                artist_id = purrr::map_chr(artists, ~ toString(.x$id)),
                artist_name = purrr::map_chr(artists, ~ toString(.x$name))
                ) %>%
            dplyr::select(
                -artists,
                -href,
                -is_local,
                -is_playable,
                -preview_url,
                -disc_number,
                -uri,
                -album.artists,
                -album.href,
                -album.id,
                -album.images,
                -album.is_playable,
                -album.name,
                -album.release_date,
                -album.release_date_precision,
                -album.total_tracks,
                -album.type,
                -album.uri,
                -album.external_urls.spotify,
                -external_ids.isrc,
                -external_urls.spotify
            ) %>%
            dplyr::rename(
                track_id = id,
                track_name = name,
                album_type = album.album_type
            )
    result
}
```

```{r | new get_genre_artists}
get_genre_artists <- function(genre, limit = 20, offset = 0, authorization = get_spotify_access_token()){
    url <- "https://api.spotify.com/v1/search"
    parameters <- list(
        q = stringr::str_glue('genre:"{genre}"'),
        type = "artist",
        market = "US",
        limit = limit,
        offset = offset,
        access_token = authorization
    )

    result <- httr::RETRY("GET", url, query = parameters, encode = "json", terminate_on = c(401, 403, 404))

    httr::stop_for_status(result)

    result <- jsonlite::fromJSON(httr::content(result, as = 'text', encoding = 'UTF-8'),
                    flatten = TRUE)$artists$items

    result <- result %>%
              dplyr::select(
                -href,
                -images,
                -uri,
                -external_urls.spotify,
                -followers.href
              ) %>% 
              dplyr::rename(
                artist_id = id,
                artist_name = name,
                followers_total = followers.total
              )
}
```

```{r | new get_genre_summary}
get_genre_summary <- function(genre, authorization = get_spotify_access_token()){
    tracks <- get_genre_tracks(genre, authorization = authorization)

    features <- get_track_audio_features(tracks$track_id, authorization = authorization)

    summary <- features %>%
               dplyr::select(danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, mode) %>%
               dplyr::summarize(dplyr::across(dplyr::everything(), list(mean = mean, sd = sd), na.rm = TRUE))

    genre <- data.frame(genre = genre)

    result <- merge(genre, summary)

    result
}
```

```{r | new get_genre_track_features}
get_genre_track_features <- function(genre, authorization = get_spotify_access_token()){
    tracks <- get_genre_tracks(genre, authorization = authorization)

    features <- get_track_audio_features(tracks$track_id, authorization = authorization)

    result <- dplyr::left_join(tracks, features, by = "track_id") %>%
              dplyr::select(
                -duration_ms.x
              ) %>%
              dplyr::rename(
                duration_ms = duration_ms.y
                )

    result
}
```